### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by emcor01** [znort987/blockparser#48]
I cannot run blockparser due to this Error:

user@ubuntu:~/blockparser$ ./parser all
info: mem at start = 0.000 Gigs
info: starting command "allBalances"
info: loading block chain from directory: /home/user/.bitcoin
info: block chain size = 72.788 Gigs
info: initializing hash tables
Segmentation fault (core dumped)

Does anyone have a solution?

**Comment by znort987** [comment]
How much RAM and SWAP do you have in your VM ?Less than 64GB and blockparser is going to crash.

```
On Tuesday, June 14, 2016 9:45 AM, emcor01 <notifications@github.com> wrote:
```

 I cannot run blockparser due to this Error:user@ubuntu:~/blockparser$ ./parser all
info: mem at start = 0.000 Gigs
info: starting command "allBalances"
info: loading block chain from directory: /home/user/.bitcoin
info: block chain size = 72.788 Gigs
info: initializing hash tables
Segmentation fault (core dumped)Does anyone have a solution?—

**Comment by hamnaz** [comment]
./parser all

info: mem at start = 0.000 Gigs
info: starting command "allBalances"
info: loading block chain from directory: /home/solarbusinesspk/.bitcoin
info: block chain size = 136.647 Gigs
info: initializing hash tables
Segmentation fault

its new bitcoin core 0.16.3 installed and full blocks downloaded
on every command of block parser same result

any solution
